Change according to stress test
MaxShoshin/LoadingIndicator pull request #6
Opened 2021-03-01 13:15 UTC by SMelikhov

Create stress application which in UI thread sleep from 40 ms to 80 ms and set up abort timer to 50 ms. In such environment test 500 iterations. While we have application inactive we still have problem with Thread.Abort until apply this fix

2021-03-01 14:42 UTC, MaxShoshin commented
Could you share test application?

It is very strange: you remove `Interlocked`, therefore a lot of race conditions are available. 

Currently I expect issue (in main code branch) when UI thread exited from SafeSelect method and Timer callback just try to Abort thread.

So we need to wait in `ResetAbort` method `ThreadAbortedException`. And reset abort right after `control.Select();`.

2021-03-01 14:43 UTC, MaxShoshin requested changes

2021-03-01 14:43 UTC, MaxShoshin commented on src/LoadingIndicator.WinForms/SelectControlExtensions.cs
> -                if (Interlocked.CompareExchange(ref _flag, AbortRequested, InitialValue) == InitialValue)
It is very strange that you remove all multithreading code and it still worked...

2021-03-01 15:46 UTC, SMelikhov commented on src/LoadingIndicator.WinForms/SelectControlExtensions.cs
> -                if (Interlocked.CompareExchange(ref _flag, AbortRequested, InitialValue) == InitialValue)
https://github.com/SMelikhov/ThreadAbort/tree/main/ThreadAbort
SelectControlExtensions - current version
SelectControlExtensions2 - changed version
To reproduce start without debugging and push the button Original.
Then bring another application to front and wait for several minutes, make tool active again and after several iterations exception occurred. Also helps to reproduce minimize RDP and wait for ~2 minutes.

2021-03-01 16:06 UTC, MaxShoshin commented on src/LoadingIndicator.WinForms/SelectControlExtensions.cs
> -                if (Interlocked.CompareExchange(ref _flag, AbortRequested, InitialValue) == InitialValue)
It seems that the link pointed to private repository.
Could you provide acccess/make public/create public gist?

2021-03-01 16:14 UTC, SMelikhov commented on src/LoadingIndicator.WinForms/SelectControlExtensions.cs
> -                if (Interlocked.CompareExchange(ref _flag, AbortRequested, InitialValue) == InitialValue)
I have made it visible

2021-03-01 20:07 UTC, MaxShoshin commented on src/LoadingIndicator.WinForms/SelectControlExtensions.cs
> -                if (Interlocked.CompareExchange(ref _flag, AbortRequested, InitialValue) == InitialValue)
The same issue in both variants.

2021-03-01 20:09 UTC, MaxShoshin commented
I've applied #5 to fix this issue

2021-03-02 09:50 UTC, closed without merging

2021-03-02 09:51 UTC, SMelikhov commented
I have tested #5 to fix this issue. Exception was not reproduce.